### ISSUE TITLE
History lines are cleared when performing a search

### ISSUE THREAD

**Issue by CreativeCactus** [cantino/mcfly#107]
As the below shows, after performing a search (even if aborting), the `$MCFLY_HISTORY` file appears to be cleared, resulting in normal "history lines" navigation (up arrow) not working after the `history -cr $MCFLY_HISTORY`.

![image](https://user-images.githubusercontent.com/12624092/96685970-355f8380-13c1-11eb-8395-ea8a05558788.png)

`GNU bash, version 4.4.23(1)-release`

**Comment by cantino** [comment]
That's odd, I've never seen that behavior.

**Comment by kuehnelth** [comment]
Hi, I have the same problem. I'm on bash version 5.1.4.
Going back to mcfly version 0.5.1 or reverting commit 440249c9f1fe2a2e4fb58ef05de5ba265bb0d927 fixes the issue.

I think the `${READLINE_LINE[@]} > $MCFLY_HISTORY` added by this commit should be `${READLINE_LINE[@]} >> $MCFLY_HISTORY` instead. So it appends to the history file instead of overwriting it.

**Comment by cantino** [comment]
Thank you @kuehnelth, that makes sense!

**Comment by cantino** [comment]
I just pushed a fix to the repo— could you confirm that this fixes your bug @CreativeCactus?

**Comment by cantino** [comment]
Released in v0.5.3

**Comment by kuehnelth** [comment]
Thanks. Just installed it. Works fine now.

**Comment by cantino** [comment]
Thanks for checking!
