### ISSUE TITLE
Please consider adding a config to enable/disable the tip/banner.

### ISSUE THREAD

**Issue by cocoonkid** [cantino/mcfly#140]
Please consider adding a config to enable/disable the tip/banner.

**Comment by michaelnavs** [comment]
I would like to claim this one and try to implement it. 

I have one idea on a potential solution. We add a boolean property to Settings called disable_menu. By default, it will be false. If users want to disable the menu, they can use an env variable to disable it. If the disable_menu is false, the menu will be displayed, otherwise disable the menu.

- settings.rs
```rust
pub struct Settings {
    // insert other properties
    pub disable_menu: bool,
}

impl Settings {
    pub fn parse_args() -> Settings {
        settings.disable_menu = match env::var_os("MCFLY_DISABLE_MENU") {
            Some(_val) => true,
            None => false,
        };
    }
}
```

- interface.rs
```rust
fn menubar<W: Write>(&self, screen: &mut W) {
    if !self.settings.disable_menu {
        // show menu
    }
 }
```

**Comment by cantino** [comment]
This seems reasonable @michaelnavs!
