### ISSUE TITLE
Stop working after sourcing ~/.zshrc

### ISSUE THREAD

**Issue by andgineer** [cantino/mcfly#219]
MacOS 11.6.2
iTerm 3.4.14
zsh 5.8 (with only git plugin)
at the end of .zshrc I have `eval "$(mcfly init zsh)"`

I also have fig.io installed

It works just after starting iTerm2, in default and newly created tabs

But after `.~/.zshrc` ^r is binded to standard back search

**Comment by SamShowalter** [comment]
I am also having this issue.

**Comment by cantino** [comment]
Hey @andgineer, I'm not sure why it wouldn't be working.

**Comment by dasebasto** [comment]
Something in your .zshrc is probably binding ^r to standard or custom history search.

I had the same issue.
The culprit line in my .zshrc was:
`source $ZSH/oh-my-zsh.sh`

The bug only occurs when you source .zshrc more than once, because `$(mcfly init zsh)` contains this:

```
# Avoid loading this file more than once
if [[ "$__MCFLY_LOADED" == "loaded" ]]; then
  return 0
fi
__MCFLY_LOADED="loaded"
[...]
  bindkey '^R' mcfly-history-widget
```

Quick fix for me was to add
`bindkey '^R' mcfly-history-widget` *before* `eval "$(mcfly init zsh)` in my .zshrc


I believe the current behavior of `eval "$(mcfly init zsh)` should be changed. It should:
- always bind ^R
- not contain return statements that have the nasty side effect of skipping all the following lines in .zshrc

**Comment by andgineer** [comment]
Thank you!
In fact it only help when I placed `bindkey` AFTER `source $ZSH/oh-my-zsh.sh`

**Comment by Jayphen** [comment]
I have the same problem (also with oh-my-zsh). I have tried putting `bindkey` before and after sourcing `oh-my-zsh`, but without luck. ctrl-r always get rebound back to the default search.

**Comment by tombh** [comment]
As mentioned in #254, a quick fix for this is to, instead of `eval "$(mcfly init zsh)"`, just use `source <(mcfly init zsh)`.
